# Menus
bindd = SUPER, SPACE, Launch apps, exec, ~/.dotfiles/bin/launch-walker
bindd = SUPER CTRL, E, Emoji picker, exec, ~/.dotfiles/bin/launch-walker -m symbols
bindd = SUPER CTRL, C, Capture menu, exec, ~/.dotfiles/bin/menu capture
bindd = SUPER CTRL, O, Toggle menu, exec, ~/.dotfiles/bin/menu toggle
bindd = SUPER ALT, SPACE, Main menu, exec, ~/.dotfiles/bin/menu
bindd = SUPER SHIFT, code:201, Main menu, exec, ~/.dotfiles/bin/menu
bindd = SUPER, ESCAPE, System menu, exec, ~/.dotfiles/bin/menu system
bindld = , XF86PowerOff, Power menu, exec, ~/.dotfiles/bin/menu system
bindd = SUPER, PERIOD, Show key bindings, exec, ~/.dotfiles/bin/menu-keybindings
bindd = , XF86Calculator, Calculator, exec, gnome-calculator

# Aesthetics
bindd = SUPER SHIFT, SPACE, Toggle top bar, exec, ~/.dotfiles/bin/toggle-waybar
bindd = SUPER CTRL, SPACE, Theme background menu, exec, ~/.dotfiles/bin/menu background
bindd = SUPER, BACKSPACE, Toggle window transparency, exec, ~/.dotfiles/bin/hyprland-active-window-transparency-toggle

# Notifications
bindd = SUPER, COMMA, Dismiss last notification, exec, swaync-client --close-latest
bindd = SUPER SHIFT, COMMA, Dismiss all notifications, exec, swaync-client --close-all
bindd = SUPER CTRL, COMMA, Toggle silencing notifications, exec, swaync-client -d
bindd = SUPER CTRL ALT, COMMA, Toggle Notification Panel, exec, swaync-client -t

# Toggles
bindd = SUPER CTRL, I, Toggle locking on idle, exec, ~/.dotfiles/bin/toggle-idle
bindd = SUPER CTRL, N, Toggle nightlight, exec, ~/.dotfiles/bin/toggle-nightlight

# Captures
bindd = , PRINT, Screenshot, exec, ~/.dotfiles/bin/capture-screenshot
bindd = ALT, PRINT, Screenrecording, exec, ~/.dotfiles/bin/menu screenrecord
bindd = SUPER, PRINT, Color picker, exec, pkill hyprpicker || hyprpicker -a

# File sharing
bindd = SUPER CTRL, S, Share, exec, ~/.dotfiles/bin/menu share

# Control panels
bindd = SUPER CTRL, A, Audio controls, exec, ~/.dotfiles/bin/launch-audio
bindd = SUPER CTRL, B, Bluetooth controls, exec, ~/.dotfiles/bin/launch-bluetooth
bindd = SUPER CTRL, W, Wifi controls, exec, ~/.dotfiles/bin/launch-wifi
bindd = SUPER CTRL, T, Activity, exec, ~/.dotfiles/bin/launch-tui btop

# Dictation
bindd = SUPER CTRL, X, Toggle dictation, exec, voxtype record toggle

# Zoom
bindd = SUPER CTRL, Z, Zoom in, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float + 1')
bindd = SUPER CTRL ALT, Z, Reset zoom, exec, hyprctl keyword cursor:zoom_factor 1

# Lock system
bindd = SUPER CTRL, L, Lock system, exec, ~/.dotfiles/bin/system-lock
