# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- ghostty # --dir="$(omarchy-cmd-terminal-cwd)" tmux new
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- ghostty # --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, ~/.dotfiles/bin/launch-browser
bindd = SUPER SHIFT, F, File manager, exec, ~/.dotfiles/bin/launch-tui yazi
bindd = SUPER SHIFT, B, Browser, exec, ~/.dotfiles/bin/launch-browser
bindd = SUPER SHIFT, M, Music, exec, ~/.dotfiles/bin/launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, ~/.dotfiles/bin/launch-editor
bindd = SUPER SHIFT, D, Whiteboard, exec, ~/Desktop/appimages/drawy.AppImage
bindd = SUPER SHIFT, T, Typora, exec, uwsm-app -- typora --enable-wayland-ime
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password
bindd = SUPER SHIFT ALT, B, Browser (private), exec, ~/.dotfiles/bin/launch-browser --private
bindd = CTRL SHIFT, ESCAPE, Activity, exec, ~/.dotfiles/bin/launch-tui btop

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, A, Claude, exec, uwsm-app -- claude-desktop 
bindd = SUPER SHIFT, C, Calendar, exec, ~/.dotfiles/bin/launch-webapp "https://calendar.notion.so"
bindd = SUPER SHIFT, E, Email, exec, ~/.dotfiles/bin/launch-webapp "https://mail.notion.so"
bindd = SUPER SHIFT, Y, YouTube, exec, ~/.dotfiles/bin/launch-webapp "https://youtube.com/"
bindd = SUPER SHIFT, W, WhatsApp, exec, ~/.dotfiles/bin/launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"

# Hamza's Keybindings
input {
}

unbind = SUPER, J
unbind = SUPER, K
unbind = SUPER, W

bindd = SUPER, COMMA, Dismiss last notification, exec, swaync-client --close-latest
bindd = SUPER ALT SHIFT, COMMA, Dismiss all notifications, exec, swaync-client --close-all
bindd = SUPER ALT CTRL, COMMA, Toggle silencing notifications, exec, swaync-client -d
bindd = SUPER CTRL ALT, COMMA, Toggle Notification Panel, exec, swaync-client -t

bindd = SUPER, Q, Close window, killactive
bindd = SUPER, PERIOD, Show key bindings, exec, omarchy-menu-keybindings

bindd = SUPER, H, Move window focus left, movefocus, l
bindd = SUPER, J, Move window focus down, movefocus, d
bindd = SUPER, K, Move window focus up, movefocus, u
bindd = SUPER, L, Move window focus right, movefocus, r

bindd = SUPER SHIFT, H, Swap window to the left, swapwindow, l
bindd = SUPER SHIFT, J, Swap window down, swapwindow, d
bindd = SUPER SHIFT, K, Swap window up, swapwindow, u
bindd = SUPER SHIFT, L, Swap window to the right, swapwindow, r

bindd = SUPER CTRL SHIFT, H, Move window to group on left, moveintogroup, l
bindd = SUPER CTRL SHIFT, J, Move window to group on bottom, moveintogroup, d
bindd = SUPER CTRL SHIFT, K, Move window to group on top, moveintogroup, u
bindd = SUPER CTRL SHIFT, L, Move window to group on right, moveintogroup, r
