# Application bindings
bindd = SHIFT ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
bindd = SHIFT, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = ALT SHIFT, RETURN, Browser, exec, ~/.dotfiles/bin/launch-browser
bindd = ALT SHIFT, F, File manager, exec, ~/.dotfiles/bin/launch-tui yazi
bindd = ALT SHIFT, B, Browser, exec, ~/.dotfiles/bin/launch-browser
bindd = ALT SHIFT, M, Music, exec, ~/.dotfiles/bin/launch-or-focus spotify
bindd = ALT SHIFT, N, Editor, exec, ~/.dotfiles/bin/launch-editor
bindd = ALT SHIFT, D, Whiteboard, exec, ~/Desktop/appimages/drawy.AppImage
bindd = ALT SHIFT, T, Typora, exec, uwsm-app -- typora --enable-wayland-ime
bindd = ALT SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password
bindd = CTRL SHIFT ALT, B, Browser (private), exec, ~/.dotfiles/bin/launch-browser --private
bindd = CTRL SHIFT, ESCAPE, Activity, exec, ~/.dotfiles/bin/launch-tui btop

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = ALT SHIFT, A, Claude, exec, uwsm-app -- claude-desktop 
bindd = ALT SHIFT, C, Calendar, exec, ~/.dotfiles/bin/launch-webapp "https://calendar.notion.so"
bindd = ALT SHIFT, E, Email, exec, ~/.dotfiles/bin/launch-webapp "https://mail.notion.so"
bindd = ALT SHIFT, Y, YouTube, exec, ~/.dotfiles/bin/launch-webapp "https://youtube.com/"
bindd = ALT SHIFT, W, WhatsApp, exec, ~/.dotfiles/bin/launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"

# Hamza's Keybindings
input {
    touchpad {
        disable_while_typing = true
      }
}

unbind = SUPER, J
unbind = SUPER, K
unbind = SUPER, W

bindd = ALT, COMMA, Dismiss last notification, exec, swaync-client --close-latest
bindd = ALT SHIFT, COMMA, Dismiss all notifications, exec, swaync-client --close-all
bindd = ALT CTRL, COMMA, Toggle silencing notifications, exec, swaync-client -d
bindd = CTRL ALT, COMMA, Toggle Notification Panel, exec, swaync-client -t

bindd = ALT, Q, Close window, killactive
bindd = ALT, PERIOD, Show key bindings, exec, omarchy-menu-keybindings

bindd = ALT, H, Move window focus left, movefocus, l
bindd = ALT, J, Move window focus down, movefocus, d
bindd = ALT, K, Move window focus up, movefocus, u
bindd = ALT, L, Move window focus right, movefocus, r

bindd = ALT SHIFT, H, Swap window to the left, swapwindow, l
bindd = ALT SHIFT, J, Swap window down, swapwindow, d
bindd = ALT SHIFT, K, Swap window up, swapwindow, u
bindd = ALT SHIFT, L, Swap window to the right, swapwindow, r

bindd = CTRL ALT, H, Move window to group on left, moveintogroup, l
bindd = CTRL ALT, J, Move window to group on bottom, moveintogroup, d
bindd = CTRL ALT, K, Move window to group on top, moveintogroup, u
bindd = CTRL ALT, L, Move window to group on right, moveintogroup, r
