# Application bindings
<<<<<<< HEAD
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- ghostty +new-window
bindd = SUPER SHIFT, RETURN, Browser, exec, ~/.dotfiles/bin/launch-browser
bindd = SUPER SHIFT, F, File manager, exec, ~/.dotfiles/bin/launch-tui yazi
bindd = SUPER SHIFT, B, Browser, exec, ~/.dotfiles/bin/launch-browser
bindd = SUPER SHIFT, M, Music, exec, ~/.dotfiles/bin/launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, ~/.dotfiles/bin/launch-editor
=======
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, omarchy-launch-tui yazi
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT ALT, M, Music TUI, exec, omarchy-launch-or-focus-tui cliamp
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
>>>>>>> master
bindd = SUPER SHIFT, D, Whiteboard, exec, ~/Desktop/appimages/drawy.AppImage
bindd = SUPER SHIFT, T, Typora, exec, uwsm-app -- typora --enable-wayland-ime
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password
bindd = SUPER SHIFT ALT, B, Browser (private), exec, ~/.dotfiles/bin/launch-browser --private
bindd = CTRL SHIFT, ESCAPE, Activity, exec, ~/.dotfiles/bin/launch-tui btop

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, A, Claude, exec, uwsm-app -- claude-desktop 
<<<<<<< HEAD
bindd = SUPER SHIFT, C, Calendar, exec, ~/.dotfiles/bin/launch-webapp "https://calendar.notion.so"
bindd = SUPER SHIFT, E, Email, exec, ~/.dotfiles/bin/launch-webapp "https://mail.notion.so"
bindd = SUPER SHIFT, Y, YouTube, exec, ~/.dotfiles/bin/launch-webapp "https://youtube.com/"
bindd = SUPER SHIFT, W, WhatsApp, exec, ~/.dotfiles/bin/launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
=======
bindd = SUPER SHIFT, C, Calendar, exec, omarchy-launch-webapp "https://calendar.notion.so"
bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-webapp "https://mail.notion.so"
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"
bindd = SUPER SHIFT, W, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"

# Hamza's Keybindings
input {
}

unbind = SUPER, J
unbind = SUPER, K
unbind = SUPER, W
unbind = SUPER, L

ubind = SUPER, COMMA, Dismiss last notification, exec, makoctl dismiss
ubind = SUPER SHIFT, COMMA, Dismiss all notifications, exec, makoctl dismiss --all
ubind = SUPER CTRL, COMMA, Toggle silencing notifications, exec, makoctl mode -t do-not-disturb && makoctl mode | grep -q 'do-not-disturb' && notify-send "Silenced notifications" || notify-send "Enabled notifications"
ubind = SUPER ALT, COMMA, Invoke last notification, exec, makoctl invoke
ubind = SUPER SHIFT ALT, COMMA, Restore last notification, exec, makoctl restore
>>>>>>> master

# Swaync
bindd = SUPER, COMMA, Dismiss last notification, exec, swaync-client --close-latest
bindd = SUPER ALT SHIFT, COMMA, Dismiss all notifications, exec, swaync-client --close-all
bindd = SUPER ALT CTRL, COMMA, Toggle silencing notifications, exec, swaync-client -d
bindd = SUPER CTRL ALT, COMMA, Toggle Notification Panel, exec, swaync-client -t

bindd = SUPER, PERIOD, Show key bindings, exec, ~/.dotfiles/bin/menu-keybindings
