# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# de-omarchy'd files
source = ~/.dotfiles/sources/hypr/autostart.conf
source = ~/.dotfiles/sources/hypr/bindings/media.conf
source = ~/.dotfiles/sources/hypr/bindings/clipboard.conf
source = ~/.dotfiles/sources/hypr/bindings/tiling.conf
source = ~/.dotfiles/sources/hypr/bindings/utilities.conf
source = ~/.dotfiles/sources/hypr/envs.conf
source = ~/.dotfiles/sources/hypr/looknfeel.conf
source = ~/.dotfiles/sources/hypr/input.conf
source = ~/.dotfiles/sources/hypr/windows.conf
source = ~/.dotfiles/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/autostart.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, class:qemu

# Toggle config flags dynamically
source = ~/.local/state/omarchy/toggles/hypr/*.conf
