-- Generated from consolidated autostart.conf
hl.on("hyprland.start", function()
  hl.exec_cmd("uwsm-app -- hypridle")
  hl.exec_cmd("uwsm-app -- waybar")
  hl.exec_cmd("uwsm-app -- swaybg -i ~/.dotfiles/theme/backgrounds/bg1.png -m fill")
  hl.exec_cmd("uwsm-app -- swayosd-server")
  hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
  hl.exec_cmd("~/.dotfiles/bin/powerprofiles-init")
  hl.exec_cmd("systemctl --user import-environment $(env | cut -d'=' -f 1)")
  hl.exec_cmd("dbus-update-activation-environment --systemd --all")
  hl.exec_cmd("uwsm app -- hyprsunset")
  hl.exec_cmd("hyprctl setcursor Moga 24")
  hl.exec_cmd("uwsm-app -- swaync")
  hl.exec_cmd("greenclip daemon")
end)
